version: "3.2"

networks:
   host:

services:

 redis:
    image: "redis:alpine"

    #    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

    ports:
     - "6379:6379"
    restart: always
    volumes:
     - /data:/bitnami/redis/data
    networks:
      - host

 zerodha:
   image: "zerodha:latest"
   build: .
   environment:
     - DEMO_REDIS_ADDR=redis:6379
     - DEMO_APP_ADDR=0.0.0.0:8000
   ports:
     - "8000:8000"
   depends_on:
       - "redis"
   restart: always
   networks:
     - host

volumes:
  redis_data:
