---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: go-app             # Unique name of the Kubernetes resource
  namespace: demo-ops
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: go-app          # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: go-app 
    spec:
      containers:
      - name: go-app
        image: h04x00/zerodha-task:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 8000  # Should match the port number that the Go application listens on  
        livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 15
        readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
        env:                     # Environment variables passed to the container
          - name: DEMO_APP_ADDR
            value: "0.0.0.0:8000"
          - name: DEMO_REDIS_ADDR
            value: "redis-master:6379"    
---
apiVersion: v1
kind: Service # Type of kubernetes resource
metadata:
  name: go-app-service     # Unique name of the resource
  namespace: demo-ops
spec:
  type: NodePort                 # Expose the Pods by opening a port on each Node and proxying it to the service.
  ports:                         
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: go-app            # Map any pod with label `app=go-app` to this service
